supportedArchitectures:
  os:
    - current
  cpu:
    - current

publicHoistPattern:
  - '@img/sharp-*'

allowBuilds:
  '@zerob13/nativekit': false
  '@parcel/watcher': false
  '@tailwindcss/oxide': true
  better-sqlite3-multiple-ciphers: false
  classic-level: true
  electron: true
  electron-winstaller: true
  esbuild: false
  lzo: true
  maplibre-gl: false
  node-pty: false
  protobufjs: false
  sharp: false
  vue-demi: false
