import type { z } from 'zod'
import type { RouteContract } from './common'
import { acpTerminalInputRoute, acpTerminalKillRoute } from './routes/acp-terminal.routes'
import {
  browserAttachCurrentWindowRoute,
  browserClearSandboxDataRoute,
  browserDestroyRoute,
  browserDetachRoute,
  browserGetStatusRoute,
  browserGoBackRoute,
  browserGoForwardRoute,
  browserLoadUrlRoute,
  browserReloadRoute,
  browserUpdateCurrentWindowBoundsRoute
} from './routes/browser.routes'
import {
  chatRespondToolInteractionRoute,
  chatSendMessageRoute,
  chatSteerActiveTurnRoute,
  chatStopStreamRoute
} from './routes/chat.routes'
import {
  databaseSecurityChangePasswordRoute,
  databaseSecurityDisableRoute,
  databaseSecurityEnableRoute,
  databaseSecurityGetStatusRoute,
  databaseSecurityRepairSchemaRoute
} from './routes/database-security.routes'
import { debugCreateMockChatSessionRoute } from './routes/debug.routes'
import {
  memoryAddRoute,
  memoryArchiveRoute,
  memoryApprovePersonaDraftRoute,
  memoryClearRoute,
  memoryDeleteRoute,
  memoryGetSourceSpanRoute,
  memoryGetByIdsRoute,
  memoryGetHealthRoute,
  memoryGetArchiveCandidateLifecyclePreviewRoute,
  memoryGetLifecycleRoute,
  memoryGetStatusRoute,
  memoryListAuditEventsRoute,
  memoryListConflictsRoute,
  memoryListPersonaDraftsRoute,
  memoryListPersonaVersionsRoute,
  memoryListRoute,
  memoryListViewManifestsRoute,
  memoryRejectPersonaDraftRoute,
  memoryReindexRoute,
  memoryResolveConflictRoute,
  memoryRestoreRoute,
  memoryRollbackPersonaRoute,
  memorySearchRoute,
  memorySetPersonaAnchorRoute,
  memoryUpdateRoute
} from './routes/memory.routes'
import {
  configAddCustomPromptRoute,
  configAddManualAcpAgentRoute,
  configAddSystemPromptRoute,
  configClearDefaultSystemPromptRoute,
  configCreateDeepChatAgentRoute,
  configDeleteCustomPromptRoute,
  configDeleteDeepChatAgentRoute,
  configDeleteSystemPromptRoute,
  configGetAcpRegistryIconMarkupRoute,
  configGetAcpSharedMcpSelectionsRoute,
  configGetAcpStateRoute,
  configGetAgentMcpSelectionsRoute,
  configGetAwsBedrockCredentialRoute,
  configGetAzureApiVersionRoute,
  configGetDefaultProjectPathRoute,
  configGetDefaultSystemPromptRoute,
  configGetEntriesRoute,
  configGetFloatingButtonRoute,
  configGetGeminiSafetyRoute,
  configGetHooksNotificationsRoute,
  configGetKnowledgeConfigsRoute,
  configGetLanguageRoute,
  configGetMcpServersRoute,
  configGetProxySettingsRoute,
  configGetShortcutKeysRoute,
  configGetSkillDraftSuggestionsRoute,
  configGetSyncSettingsRoute,
  configGetSystemPromptsRoute,
  configGetThemeRoute,
  configGetUpdateChannelRoute,
  configGetVoiceAiConfigRoute,
  configEnsureAcpAgentInstalledRoute,
  configListAgentsRoute,
  configListAcpRegistryAgentsRoute,
  configListCustomPromptsRoute,
  configListManualAcpAgentsRoute,
  configOpenLoggingFolderRoute,
  configRefreshAcpRegistryRoute,
  configRefreshProviderDbRoute,
  configRemoveManualAcpAgentRoute,
  configRepairAcpAgentRoute,
  configResetDefaultSystemPromptRoute,
  configResetShortcutKeysRoute,
  configResolveDeepChatAgentConfigRoute,
  configSetAcpSharedMcpSelectionsRoute,
  configSetAcpAgentEnabledRoute,
  configSetAcpAgentEnvOverrideRoute,
  configSetAcpEnabledRoute,
  configSetAwsBedrockCredentialRoute,
  configSetAzureApiVersionRoute,
  configSetCustomPromptsRoute,
  configSetDefaultProjectPathRoute,
  configSetDefaultSystemPromptIdRoute,
  configSetDefaultSystemPromptRoute,
  configSetFloatingButtonRoute,
  configSetGeminiSafetyRoute,
  configSetHooksNotificationsRoute,
  configSetKnowledgeConfigsRoute,
  configSetLanguageRoute,
  configSetCustomProxyUrlRoute,
  configSetShortcutKeysRoute,
  configSetProxyModeRoute,
  configSetSystemPromptsRoute,
  configSetSkillDraftSuggestionsRoute,
  configSetThemeRoute,
  configSetUpdateChannelRoute,
  configTestHookCommandRoute,
  configUninstallAcpRegistryAgentRoute,
  configUpdateCustomPromptRoute,
  configUpdateDeepChatAgentRoute,
  configUpdateEntriesRoute,
  configUpdateManualAcpAgentRoute,
  configUpdateSyncSettingsRoute,
  configUpdateSystemPromptRoute,
  configUpdateVoiceAiConfigRoute
} from './routes/config.routes'
import { dialogErrorRoute, dialogRespondRoute } from './routes/dialog.routes'
import {
  deviceGetAppVersionRoute,
  deviceGetInfoRoute,
  deviceRestartAppRoute,
  deviceResetDataByTypeRoute,
  deviceSanitizeSvgRoute,
  deviceSelectDirectoryRoute,
  deviceSelectFilesRoute
} from './routes/device.routes'
import {
  fileCopyImageRoute,
  fileGetMimeTypeRoute,
  fileIsDirectoryRoute,
  filePrepareDirectoryRoute,
  filePrepareFileRoute,
  fileReadFileRoute,
  fileSaveImageRoute,
  fileWriteImageBase64Route
} from './routes/file.routes'
import {
  knowledgeAddFileRoute,
  knowledgeDeleteFileRoute,
  knowledgeGetSeparatorsForLanguageRoute,
  knowledgeGetSupportedFileExtensionsRoute,
  knowledgeGetSupportedLanguagesRoute,
  knowledgeIsSupportedRoute,
  knowledgeListFilesRoute,
  knowledgePauseAllRunningTasksRoute,
  knowledgeReAddFileRoute,
  knowledgeResumeAllPausedTasksRoute,
  knowledgeSimilarityQueryRoute,
  knowledgeValidateFileRoute
} from './routes/knowledge.routes'
import {
  mcpAddServerRoute,
  mcpCallToolRoute,
  mcpCancelSamplingRequestRoute,
  mcpClearNpmRegistryCacheRoute,
  mcpCompleteServerAuthFromCallbackUrlRoute,
  mcpGetClientsRoute,
  mcpGetEnabledRoute,
  mcpGetNpmRegistryStatusRoute,
  mcpGetPromptRoute,
  mcpGetServerAuthStatusRoute,
  mcpGetServersRoute,
  mcpIsServerRunningRoute,
  mcpListPromptsRoute,
  mcpListResourcesRoute,
  mcpListToolDefinitionsRoute,
  mcpLogoutServerAuthRoute,
  mcpReadResourceRoute,
  mcpRefreshNpmRegistryRoute,
  mcpRemoveServerRoute,
  mcpRouterGetApiKeyRoute,
  mcpRouterInstallServerRoute,
  mcpRouterIsServerInstalledRoute,
  mcpRouterListServersRoute,
  mcpRouterSetApiKeyRoute,
  mcpRouterUpdateServersAuthRoute,
  mcpSetAutoDetectNpmRegistryRoute,
  mcpSetCustomNpmRegistryRoute,
  mcpSetEnabledRoute,
  mcpSetServerEnabledRoute,
  mcpStartServerAuthRoute,
  mcpStartServerRoute,
  mcpStopServerRoute,
  mcpSubmitSamplingDecisionRoute,
  mcpUpdateServerRoute
} from './routes/mcp.routes'
import {
  modelsAddCustomRoute,
  modelsExportConfigsRoute,
  modelsGetCapabilitiesRoute,
  modelsGetConfigRoute,
  modelsGetProviderCatalogRoute,
  modelsGetProviderConfigsRoute,
  modelsHasUserConfigRoute,
  modelsImportConfigsRoute,
  modelsListRuntimeRoute,
  modelsRemoveCustomRoute,
  modelsResetConfigRoute,
  modelsSetBatchStatusRoute,
  modelsSetConfigRoute,
  modelsSetStatusRoute,
  modelsTranscribeAudioRoute,
  modelsUpdateCustomRoute
} from './routes/models.routes'
import {
  onboardingCompleteRoute,
  onboardingGetStateRoute,
  onboardingResetRoute,
  onboardingSetStepStatusRoute,
  onboardingStartRoute
} from './routes/onboarding.routes'
import {
  nowledgeMemGetConfigRoute,
  nowledgeMemTestConnectionRoute,
  nowledgeMemUpdateConfigRoute
} from './routes/nowledgeMem.routes'
import {
  oauthGithubCopilotStartDeviceFlowLoginRoute,
  oauthGithubCopilotStartLoginRoute,
  oauthOpenAICodexCancelLoginRoute,
  oauthOpenAICodexCompleteBrowserLoginFromUrlRoute,
  oauthOpenAICodexGetStatusRoute,
  oauthOpenAICodexLogoutRoute,
  oauthOpenAICodexStartBrowserLoginRoute
} from './routes/oauth.routes'
import {
  remoteControlCancelFeishuAuthRoute,
  remoteControlCancelFeishuInstallRoute,
  remoteControlClearChannelPairCodeRoute,
  remoteControlCreateChannelPairCodeRoute,
  remoteControlGetChannelBindingsRoute,
  remoteControlGetChannelPairingSnapshotRoute,
  remoteControlGetChannelSettingsRoute,
  remoteControlGetChannelStatusRoute,
  remoteControlGetTelegramStatusRoute,
  remoteControlGetWeixinIlinkStatusRoute,
  remoteControlListChannelsRoute,
  remoteControlRemoveChannelBindingRoute,
  remoteControlRemoveChannelPrincipalRoute,
  remoteControlRemoveWeixinIlinkAccountRoute,
  remoteControlRestartWeixinIlinkAccountRoute,
  remoteControlSaveChannelSettingsRoute,
  remoteControlStartFeishuAuthRoute,
  remoteControlStartFeishuInstallRoute,
  remoteControlStartWeixinIlinkLoginRoute,
  remoteControlWaitForFeishuAuthRoute,
  remoteControlWaitForFeishuInstallRoute,
  remoteControlWaitForWeixinIlinkLoginRoute
} from './routes/remote-control.routes'
import {
  cronJobsDeleteRoute,
  cronJobsGetRunRoute,
  cronJobsGetSchedulerStatusRoute,
  cronJobsListDeliveriesRoute,
  cronJobsListRoute,
  cronJobsListRunsRoute,
  cronJobsPreviewScheduleRoute,
  cronJobsReconcileSchedulerRoute,
  cronJobsRestartSchedulerRoute,
  cronJobsRunNowRoute,
  cronJobsToggleRoute,
  cronJobsValidateScheduleRoute,
  cronJobsUpsertRoute
} from './routes/cronJobs.routes'
import {
  providersAddRoute,
  providersGetAcpProcessConfigOptionsRoute,
  providersGetEmbeddingDimensionsRoute,
  providersGetKeyStatusRoute,
  providersGetRateLimitStatusRoute,
  providersImportApplyRoute,
  providersImportScanRoute,
  providersListDefaultsRoute,
  providersListModelsRoute,
  providersListOllamaModelsRoute,
  providersListOllamaRunningModelsRoute,
  providersListRoute,
  providersListSummariesRoute,
  providersPullOllamaModelRoute,
  providersRefreshModelsRoute,
  providersRemoveRoute,
  providersReorderRoute,
  providersRunAcpDebugActionRoute,
  providersSetByIdRoute,
  providersSyncModelScopeMcpServersRoute,
  providersTestConnectionRoute,
  providersUpdateRateLimitRoute,
  providersUpdateRoute,
  providersWarmupAcpProcessRoute
} from './routes/providers.routes'
import {
  projectArchiveEnvironmentRoute,
  projectListEnvironmentsRoute,
  projectListRecentRoute,
  projectOpenDirectoryRoute,
  projectPathExistsRoute,
  projectRemoveEnvironmentRoute,
  projectReorderEnvironmentsRoute,
  projectRestoreEnvironmentRoute,
  projectSelectDirectoryRoute
} from './routes/project.routes'
import {
  pluginsDisableRoute,
  pluginsEnableRoute,
  pluginsGetRoute,
  pluginsInvokeActionRoute,
  pluginsListRoute
} from './routes/plugins.routes'
import {
  settingsActivityListRoute,
  settingsGetSnapshotRoute,
  settingsListSystemFontsRoute,
  settingsUpdateRoute
} from './routes/settings.routes'
import {
  shortcutDestroyRoute,
  shortcutRegisterRoute,
  shortcutUnregisterRoute
} from './routes/shortcut.routes'
import { startupGetBootstrapRoute } from './routes/startup.routes'
import {
  sessionsActivateRoute,
  sessionsClearMessagesRoute,
  sessionsCompactRoute,
  sessionsConvertPendingInputToSteerRoute,
  sessionsCreateRoute,
  sessionsDeleteAgentSessionsRoute,
  sessionsDeleteMessageRoute,
  sessionsDeletePendingInputRoute,
  sessionsDeleteRoute,
  sessionsDeactivateRoute,
  sessionsEditUserMessageRoute,
  sessionsEnsureAcpDraftRoute,
  sessionsExportMessageTapeReplaySliceRoute,
  sessionsExportRoute,
  sessionsForkRoute,
  sessionsGetAcpSessionCommandsRoute,
  sessionsGetAcpSessionConfigOptionsRoute,
  sessionsGetActiveRoute,
  sessionsGetAgentsRoute,
  sessionsGetAgentTransferImpactRoute,
  sessionsGetDisabledAgentToolsRoute,
  sessionsGetLightweightByIdsRoute,
  sessionsGetGenerationSettingsRoute,
  sessionsGetPermissionModeRoute,
  sessionsGetSearchResultsRoute,
  sessionsGetTapeContextRoute,
  sessionsGetUsageDashboardRoute,
  sessionsListLightweightRoute,
  sessionsListMessagesPageRoute,
  sessionsListRoute,
  sessionsListMessageTracesRoute,
  sessionsListPendingInputsRoute,
  sessionsMoveAgentSessionsRoute,
  sessionsMoveQueuedInputRoute,
  sessionsMoveToAgentRoute,
  sessionsQueuePendingInputRoute,
  sessionsRenameRoute,
  sessionsRetryRtkHealthCheckRoute,
  sessionsRetryMessageRoute,
  sessionsRestoreRoute
} from './routes/sessions.routes'
import {
  sessionsSearchHistoryRoute,
  sessionsSetAcpSessionConfigOptionRoute,
  sessionsSetModelRoute,
  sessionsSetPermissionModeRoute,
  sessionsSetProjectDirRoute,
  sessionsSetSubagentEnabledRoute,
  sessionsSteerPendingInputRoute,
  sessionsTogglePinnedRoute,
  sessionsTranslateTextRoute,
  sessionsUpdateDisabledAgentToolsRoute,
  sessionsUpdateGenerationSettingsRoute,
  sessionsUpdateQueuedInputRoute
} from './routes/sessions.routes'
import {
  skillsGetActiveRoute,
  skillsGetDirectoryRoute,
  skillsGetExtensionRoute,
  skillsGetFolderTreeRoute,
  skillsGetSyncConfigRoute,
  skillsExecuteSyncDirectoryExportRoute,
  skillsExecuteSyncDirectoryImportRoute,
  skillsInstallFromGitRoute,
  skillsInstallFromFolderRoute,
  skillsInstallFromUrlRoute,
  skillsInstallFromZipRoute,
  skillsListCatalogRoute,
  skillsListMetadataRoute,
  skillsListScriptsRoute,
  skillsOpenFolderRoute,
  skillsPreviewSyncDirectoryExportRoute,
  skillsPreviewSyncDirectoryImportRoute,
  skillsReadFileRoute,
  skillsScanGitRepoRoute,
  skillsSaveExtensionRoute,
  skillsSaveWithExtensionRoute,
  skillsSetActiveRoute,
  skillsSetDisabledRoute,
  skillsSetSyncDirectoryRoute,
  skillsUninstallRoute,
  skillsUpdateFileRoute
} from './routes/skills.routes'
import {
  skillSyncAcknowledgeDiscoveriesRoute,
  skillSyncExecuteAdoptAgentSkillRoute,
  skillSyncExecuteExportRoute,
  skillSyncExecuteImportRoute,
  skillSyncExecuteLinkDeepChatSkillsRoute,
  skillSyncGetAgentDetailRoute,
  skillSyncGetAgentSkillDetailRoute,
  skillSyncGetNewDiscoveriesRoute,
  skillSyncGetRegisteredToolsRoute,
  skillSyncPreviewAdoptAgentSkillRoute,
  skillSyncPreviewExportRoute,
  skillSyncPreviewImportRoute,
  skillSyncPreviewLinkDeepChatSkillsRoute,
  skillSyncRemoveAgentSkillLinkRoute,
  skillSyncRepairAgentSkillLinkRoute,
  skillSyncScanAgentsRoute,
  skillSyncScanExternalToolsRoute
} from './routes/skillSync.routes'
import {
  syncGetBackupStatusRoute,
  syncImportRoute,
  syncListBackupsRoute,
  syncOpenFolderRoute,
  syncStartBackupRoute,
  syncGetCloudConfigRoute,
  syncSetCloudConfigRoute,
  syncTestCloudRoute,
  syncUploadToCloudRoute,
  syncPullFromCloudRoute
} from './routes/sync.routes'
import { systemOpenSettingsRoute } from './routes/system.routes'
import { toolsListDefinitionsRoute } from './routes/tools.routes'
import {
  tabCaptureCurrentAreaRoute,
  tabNotifyRendererActivatedRoute,
  tabNotifyRendererReadyRoute,
  tabStitchImagesWithWatermarkRoute
} from './routes/tab.routes'
import {
  upgradeCheckRoute,
  upgradeClearMockRoute,
  upgradeGetStatusRoute,
  upgradeMockDownloadedRoute,
  upgradeOpenDownloadRoute,
  upgradeRestartToUpdateRoute,
  upgradeStartDownloadRoute
} from './routes/upgrade.routes'
import {
  windowCloseCurrentRoute,
  windowCloseFloatingCurrentRoute,
  windowCloseSettingsRoute,
  windowConsumePendingSettingsProviderInstallRoute,
  windowFocusMainRoute,
  windowGetCurrentStateRoute,
  windowGetRuntimeIdentityRoute,
  windowMinimizeCurrentRoute,
  windowNotifySettingsReadyRoute,
  windowPreviewFileRoute,
  windowRequeuePendingSettingsProviderInstallRoute,
  windowStartGuidedOnboardingRoute,
  windowToggleMaximizeCurrentRoute
} from './routes/window.routes'
import {
  workspaceExpandDirectoryRoute,
  workspaceGetGitDiffRoute,
  workspaceGetGitStatusRoute,
  workspaceOpenFileRoute,
  workspaceReadDirectoryRoute,
  workspaceReadFilePreviewRoute,
  workspaceRegisterRoute,
  workspaceResolveMarkdownLinkedFileRoute,
  workspaceRevealFileInFolderRoute,
  workspaceSearchFilesRoute,
  workspaceUnregisterRoute,
  workspaceUnwatchRoute,
  workspaceWatchRoute
} from './routes/workspace.routes'

export * from './routes/browser.routes'
export * from './routes/acp-terminal.routes'
export * from './routes/chat.routes'
export * from './routes/config.routes'
export * from './routes/database-security.routes'
export * from './routes/debug.routes'
export * from './routes/dialog.routes'
export * from './routes/device.routes'
export * from './routes/file.routes'
export * from './routes/knowledge.routes'
export * from './routes/mcp.routes'
export * from './routes/memory.routes'
export * from './routes/models.routes'
export * from './routes/nowledgeMem.routes'
export * from './routes/onboarding.routes'
export * from './routes/oauth.routes'
export * from './routes/plugins.routes'
export * from './routes/providers.routes'
export * from './routes/project.routes'
export * from './routes/remote-control.routes'
export * from './routes/cronJobs.routes'
export * from './routes/settings.routes'
export * from './routes/shortcut.routes'
export * from './routes/startup.routes'
export * from './routes/sessions.routes'
export * from './routes/skills.routes'
export * from './routes/skillSync.routes'
export * from './routes/sync.routes'
export * from './routes/system.routes'
export * from './routes/tab.routes'
export * from './routes/tools.routes'
export * from './routes/upgrade.routes'
export * from './routes/window.routes'
export * from './routes/workspace.routes'

// 路由目录按块拆分并各自导出：单个巨型对象的 `typeof` 在声明输出(.d.ts)时会超过
// TS 的类型序列化上限触发 TS7056。拆成多块后每块单独序列化，合并类型只保存引用，
// 既绕过上限又保留逐路由精确的输入/输出类型。新增路由追加到任意一块即可，保持各块体量适中。
const DEEPCHAT_ROUTE_CATALOG_PART_1 = {
  [acpTerminalInputRoute.name]: acpTerminalInputRoute,
  [acpTerminalKillRoute.name]: acpTerminalKillRoute,
  [shortcutRegisterRoute.name]: shortcutRegisterRoute,
  [shortcutUnregisterRoute.name]: shortcutUnregisterRoute,
  [shortcutDestroyRoute.name]: shortcutDestroyRoute,
  [windowGetCurrentStateRoute.name]: windowGetCurrentStateRoute,
  [windowGetRuntimeIdentityRoute.name]: windowGetRuntimeIdentityRoute,
  [windowMinimizeCurrentRoute.name]: windowMinimizeCurrentRoute,
  [windowToggleMaximizeCurrentRoute.name]: windowToggleMaximizeCurrentRoute,
  [windowCloseCurrentRoute.name]: windowCloseCurrentRoute,
  [windowCloseFloatingCurrentRoute.name]: windowCloseFloatingCurrentRoute,
  [windowPreviewFileRoute.name]: windowPreviewFileRoute,
  [windowCloseSettingsRoute.name]: windowCloseSettingsRoute,
  [windowFocusMainRoute.name]: windowFocusMainRoute,
  [windowNotifySettingsReadyRoute.name]: windowNotifySettingsReadyRoute,
  [windowConsumePendingSettingsProviderInstallRoute.name]:
    windowConsumePendingSettingsProviderInstallRoute,
  [windowRequeuePendingSettingsProviderInstallRoute.name]:
    windowRequeuePendingSettingsProviderInstallRoute,
  [windowStartGuidedOnboardingRoute.name]: windowStartGuidedOnboardingRoute,
  [deviceGetAppVersionRoute.name]: deviceGetAppVersionRoute,
  [deviceGetInfoRoute.name]: deviceGetInfoRoute,
  [deviceSelectDirectoryRoute.name]: deviceSelectDirectoryRoute,
  [deviceSelectFilesRoute.name]: deviceSelectFilesRoute,
  [deviceRestartAppRoute.name]: deviceRestartAppRoute,
  [deviceResetDataByTypeRoute.name]: deviceResetDataByTypeRoute,
  [deviceSanitizeSvgRoute.name]: deviceSanitizeSvgRoute,
  [projectListRecentRoute.name]: projectListRecentRoute,
  [projectListEnvironmentsRoute.name]: projectListEnvironmentsRoute,
  [projectReorderEnvironmentsRoute.name]: projectReorderEnvironmentsRoute,
  [projectArchiveEnvironmentRoute.name]: projectArchiveEnvironmentRoute,
  [projectRestoreEnvironmentRoute.name]: projectRestoreEnvironmentRoute,
  [projectRemoveEnvironmentRoute.name]: projectRemoveEnvironmentRoute,
  [projectOpenDirectoryRoute.name]: projectOpenDirectoryRoute,
  [projectPathExistsRoute.name]: projectPathExistsRoute,
  [projectSelectDirectoryRoute.name]: projectSelectDirectoryRoute,
  [onboardingGetStateRoute.name]: onboardingGetStateRoute,
  [onboardingStartRoute.name]: onboardingStartRoute,
  [onboardingSetStepStatusRoute.name]: onboardingSetStepStatusRoute,
  [onboardingCompleteRoute.name]: onboardingCompleteRoute,
  [onboardingResetRoute.name]: onboardingResetRoute,
  [nowledgeMemGetConfigRoute.name]: nowledgeMemGetConfigRoute,
  [nowledgeMemUpdateConfigRoute.name]: nowledgeMemUpdateConfigRoute,
  [nowledgeMemTestConnectionRoute.name]: nowledgeMemTestConnectionRoute,
  [oauthGithubCopilotStartLoginRoute.name]: oauthGithubCopilotStartLoginRoute,
  [oauthGithubCopilotStartDeviceFlowLoginRoute.name]: oauthGithubCopilotStartDeviceFlowLoginRoute,
  [oauthOpenAICodexGetStatusRoute.name]: oauthOpenAICodexGetStatusRoute,
  [oauthOpenAICodexStartBrowserLoginRoute.name]: oauthOpenAICodexStartBrowserLoginRoute,
  [oauthOpenAICodexCompleteBrowserLoginFromUrlRoute.name]:
    oauthOpenAICodexCompleteBrowserLoginFromUrlRoute,
  [oauthOpenAICodexCancelLoginRoute.name]: oauthOpenAICodexCancelLoginRoute,
  [oauthOpenAICodexLogoutRoute.name]: oauthOpenAICodexLogoutRoute,
  [remoteControlListChannelsRoute.name]: remoteControlListChannelsRoute,
  [remoteControlGetChannelSettingsRoute.name]: remoteControlGetChannelSettingsRoute,
  [remoteControlSaveChannelSettingsRoute.name]: remoteControlSaveChannelSettingsRoute,
  [remoteControlGetChannelStatusRoute.name]: remoteControlGetChannelStatusRoute,
  [remoteControlGetChannelBindingsRoute.name]: remoteControlGetChannelBindingsRoute,
  [remoteControlRemoveChannelBindingRoute.name]: remoteControlRemoveChannelBindingRoute,
  [remoteControlRemoveChannelPrincipalRoute.name]: remoteControlRemoveChannelPrincipalRoute,
  [remoteControlGetChannelPairingSnapshotRoute.name]: remoteControlGetChannelPairingSnapshotRoute,
  [remoteControlCreateChannelPairCodeRoute.name]: remoteControlCreateChannelPairCodeRoute,
  [remoteControlClearChannelPairCodeRoute.name]: remoteControlClearChannelPairCodeRoute,
  [remoteControlGetTelegramStatusRoute.name]: remoteControlGetTelegramStatusRoute,
  [remoteControlStartFeishuAuthRoute.name]: remoteControlStartFeishuAuthRoute,
  [remoteControlWaitForFeishuAuthRoute.name]: remoteControlWaitForFeishuAuthRoute,
  [remoteControlCancelFeishuAuthRoute.name]: remoteControlCancelFeishuAuthRoute,
  [remoteControlStartFeishuInstallRoute.name]: remoteControlStartFeishuInstallRoute,
  [remoteControlWaitForFeishuInstallRoute.name]: remoteControlWaitForFeishuInstallRoute,
  [remoteControlCancelFeishuInstallRoute.name]: remoteControlCancelFeishuInstallRoute,
  [remoteControlGetWeixinIlinkStatusRoute.name]: remoteControlGetWeixinIlinkStatusRoute,
  [remoteControlStartWeixinIlinkLoginRoute.name]: remoteControlStartWeixinIlinkLoginRoute,
  [remoteControlWaitForWeixinIlinkLoginRoute.name]: remoteControlWaitForWeixinIlinkLoginRoute,
  [remoteControlRemoveWeixinIlinkAccountRoute.name]: remoteControlRemoveWeixinIlinkAccountRoute,
  [remoteControlRestartWeixinIlinkAccountRoute.name]: remoteControlRestartWeixinIlinkAccountRoute,
  [cronJobsListRoute.name]: cronJobsListRoute,
  [cronJobsUpsertRoute.name]: cronJobsUpsertRoute,
  [cronJobsDeleteRoute.name]: cronJobsDeleteRoute,
  [cronJobsToggleRoute.name]: cronJobsToggleRoute,
  [cronJobsRunNowRoute.name]: cronJobsRunNowRoute,
  [cronJobsListRunsRoute.name]: cronJobsListRunsRoute,
  [cronJobsGetRunRoute.name]: cronJobsGetRunRoute,
  [cronJobsListDeliveriesRoute.name]: cronJobsListDeliveriesRoute,
  [cronJobsGetSchedulerStatusRoute.name]: cronJobsGetSchedulerStatusRoute,
  [cronJobsReconcileSchedulerRoute.name]: cronJobsReconcileSchedulerRoute,
  [cronJobsRestartSchedulerRoute.name]: cronJobsRestartSchedulerRoute,
  [cronJobsValidateScheduleRoute.name]: cronJobsValidateScheduleRoute,
  [cronJobsPreviewScheduleRoute.name]: cronJobsPreviewScheduleRoute,
  [pluginsListRoute.name]: pluginsListRoute,
  [pluginsGetRoute.name]: pluginsGetRoute,
  [pluginsEnableRoute.name]: pluginsEnableRoute,
  [pluginsDisableRoute.name]: pluginsDisableRoute,
  [pluginsInvokeActionRoute.name]: pluginsInvokeActionRoute
} satisfies Record<string, RouteContract>

const DEEPCHAT_ROUTE_CATALOG_PART_2 = {
  [fileGetMimeTypeRoute.name]: fileGetMimeTypeRoute,
  [filePrepareFileRoute.name]: filePrepareFileRoute,
  [filePrepareDirectoryRoute.name]: filePrepareDirectoryRoute,
  [fileReadFileRoute.name]: fileReadFileRoute,
  [fileIsDirectoryRoute.name]: fileIsDirectoryRoute,
  [fileWriteImageBase64Route.name]: fileWriteImageBase64Route,
  [fileSaveImageRoute.name]: fileSaveImageRoute,
  [fileCopyImageRoute.name]: fileCopyImageRoute,
  [knowledgeIsSupportedRoute.name]: knowledgeIsSupportedRoute,
  [knowledgeGetSupportedLanguagesRoute.name]: knowledgeGetSupportedLanguagesRoute,
  [knowledgeGetSeparatorsForLanguageRoute.name]: knowledgeGetSeparatorsForLanguageRoute,
  [knowledgeGetSupportedFileExtensionsRoute.name]: knowledgeGetSupportedFileExtensionsRoute,
  [knowledgeListFilesRoute.name]: knowledgeListFilesRoute,
  [knowledgeSimilarityQueryRoute.name]: knowledgeSimilarityQueryRoute,
  [knowledgeValidateFileRoute.name]: knowledgeValidateFileRoute,
  [knowledgeAddFileRoute.name]: knowledgeAddFileRoute,
  [knowledgeDeleteFileRoute.name]: knowledgeDeleteFileRoute,
  [knowledgeReAddFileRoute.name]: knowledgeReAddFileRoute,
  [knowledgePauseAllRunningTasksRoute.name]: knowledgePauseAllRunningTasksRoute,
  [knowledgeResumeAllPausedTasksRoute.name]: knowledgeResumeAllPausedTasksRoute,
  [workspaceRegisterRoute.name]: workspaceRegisterRoute,
  [workspaceUnregisterRoute.name]: workspaceUnregisterRoute,
  [workspaceWatchRoute.name]: workspaceWatchRoute,
  [workspaceUnwatchRoute.name]: workspaceUnwatchRoute,
  [workspaceReadDirectoryRoute.name]: workspaceReadDirectoryRoute,
  [workspaceExpandDirectoryRoute.name]: workspaceExpandDirectoryRoute,
  [workspaceRevealFileInFolderRoute.name]: workspaceRevealFileInFolderRoute,
  [workspaceOpenFileRoute.name]: workspaceOpenFileRoute,
  [workspaceReadFilePreviewRoute.name]: workspaceReadFilePreviewRoute,
  [workspaceResolveMarkdownLinkedFileRoute.name]: workspaceResolveMarkdownLinkedFileRoute,
  [workspaceGetGitStatusRoute.name]: workspaceGetGitStatusRoute,
  [workspaceGetGitDiffRoute.name]: workspaceGetGitDiffRoute,
  [workspaceSearchFilesRoute.name]: workspaceSearchFilesRoute,
  [browserGetStatusRoute.name]: browserGetStatusRoute,
  [browserLoadUrlRoute.name]: browserLoadUrlRoute,
  [browserAttachCurrentWindowRoute.name]: browserAttachCurrentWindowRoute,
  [browserUpdateCurrentWindowBoundsRoute.name]: browserUpdateCurrentWindowBoundsRoute,
  [browserDetachRoute.name]: browserDetachRoute,
  [browserDestroyRoute.name]: browserDestroyRoute,
  [browserGoBackRoute.name]: browserGoBackRoute,
  [browserGoForwardRoute.name]: browserGoForwardRoute,
  [browserReloadRoute.name]: browserReloadRoute,
  [browserClearSandboxDataRoute.name]: browserClearSandboxDataRoute,
  [tabNotifyRendererReadyRoute.name]: tabNotifyRendererReadyRoute,
  [tabNotifyRendererActivatedRoute.name]: tabNotifyRendererActivatedRoute,
  [tabCaptureCurrentAreaRoute.name]: tabCaptureCurrentAreaRoute,
  [tabStitchImagesWithWatermarkRoute.name]: tabStitchImagesWithWatermarkRoute
} satisfies Record<string, RouteContract>

const DEEPCHAT_ROUTE_CATALOG_PART_3 = {
  [configGetEntriesRoute.name]: configGetEntriesRoute,
  [configUpdateEntriesRoute.name]: configUpdateEntriesRoute,
  [configGetLanguageRoute.name]: configGetLanguageRoute,
  [configSetLanguageRoute.name]: configSetLanguageRoute,
  [configGetThemeRoute.name]: configGetThemeRoute,
  [configSetThemeRoute.name]: configSetThemeRoute,
  [configGetFloatingButtonRoute.name]: configGetFloatingButtonRoute,
  [configSetFloatingButtonRoute.name]: configSetFloatingButtonRoute,
  [configGetSyncSettingsRoute.name]: configGetSyncSettingsRoute,
  [configUpdateSyncSettingsRoute.name]: configUpdateSyncSettingsRoute,
  [configGetProxySettingsRoute.name]: configGetProxySettingsRoute,
  [configSetProxyModeRoute.name]: configSetProxyModeRoute,
  [configSetCustomProxyUrlRoute.name]: configSetCustomProxyUrlRoute,
  [configOpenLoggingFolderRoute.name]: configOpenLoggingFolderRoute,
  [configGetUpdateChannelRoute.name]: configGetUpdateChannelRoute,
  [configSetUpdateChannelRoute.name]: configSetUpdateChannelRoute,
  [configGetSkillDraftSuggestionsRoute.name]: configGetSkillDraftSuggestionsRoute,
  [configSetSkillDraftSuggestionsRoute.name]: configSetSkillDraftSuggestionsRoute,
  [configRefreshProviderDbRoute.name]: configRefreshProviderDbRoute,
  [configGetHooksNotificationsRoute.name]: configGetHooksNotificationsRoute,
  [configSetHooksNotificationsRoute.name]: configSetHooksNotificationsRoute,
  [configTestHookCommandRoute.name]: configTestHookCommandRoute,
  [configGetDefaultProjectPathRoute.name]: configGetDefaultProjectPathRoute,
  [configSetDefaultProjectPathRoute.name]: configSetDefaultProjectPathRoute,
  [configGetShortcutKeysRoute.name]: configGetShortcutKeysRoute,
  [configSetShortcutKeysRoute.name]: configSetShortcutKeysRoute,
  [configResetShortcutKeysRoute.name]: configResetShortcutKeysRoute,
  [configListCustomPromptsRoute.name]: configListCustomPromptsRoute,
  [configSetCustomPromptsRoute.name]: configSetCustomPromptsRoute,
  [configAddCustomPromptRoute.name]: configAddCustomPromptRoute,
  [configUpdateCustomPromptRoute.name]: configUpdateCustomPromptRoute,
  [configDeleteCustomPromptRoute.name]: configDeleteCustomPromptRoute,
  [configGetSystemPromptsRoute.name]: configGetSystemPromptsRoute,
  [configSetSystemPromptsRoute.name]: configSetSystemPromptsRoute,
  [configAddSystemPromptRoute.name]: configAddSystemPromptRoute,
  [configUpdateSystemPromptRoute.name]: configUpdateSystemPromptRoute,
  [configDeleteSystemPromptRoute.name]: configDeleteSystemPromptRoute,
  [configGetDefaultSystemPromptRoute.name]: configGetDefaultSystemPromptRoute,
  [configSetDefaultSystemPromptRoute.name]: configSetDefaultSystemPromptRoute,
  [configResetDefaultSystemPromptRoute.name]: configResetDefaultSystemPromptRoute,
  [configClearDefaultSystemPromptRoute.name]: configClearDefaultSystemPromptRoute,
  [configSetDefaultSystemPromptIdRoute.name]: configSetDefaultSystemPromptIdRoute,
  [configGetAcpStateRoute.name]: configGetAcpStateRoute,
  [configSetAcpEnabledRoute.name]: configSetAcpEnabledRoute,
  [configListAcpRegistryAgentsRoute.name]: configListAcpRegistryAgentsRoute,
  [configRefreshAcpRegistryRoute.name]: configRefreshAcpRegistryRoute,
  [configSetAcpAgentEnabledRoute.name]: configSetAcpAgentEnabledRoute,
  [configSetAcpAgentEnvOverrideRoute.name]: configSetAcpAgentEnvOverrideRoute,
  [configEnsureAcpAgentInstalledRoute.name]: configEnsureAcpAgentInstalledRoute,
  [configRepairAcpAgentRoute.name]: configRepairAcpAgentRoute,
  [configUninstallAcpRegistryAgentRoute.name]: configUninstallAcpRegistryAgentRoute,
  [configListManualAcpAgentsRoute.name]: configListManualAcpAgentsRoute,
  [configAddManualAcpAgentRoute.name]: configAddManualAcpAgentRoute,
  [configUpdateManualAcpAgentRoute.name]: configUpdateManualAcpAgentRoute,
  [configRemoveManualAcpAgentRoute.name]: configRemoveManualAcpAgentRoute,
  [configListAgentsRoute.name]: configListAgentsRoute,
  [configCreateDeepChatAgentRoute.name]: configCreateDeepChatAgentRoute,
  [configUpdateDeepChatAgentRoute.name]: configUpdateDeepChatAgentRoute,
  [configDeleteDeepChatAgentRoute.name]: configDeleteDeepChatAgentRoute,
  [configResolveDeepChatAgentConfigRoute.name]: configResolveDeepChatAgentConfigRoute,
  [configGetAgentMcpSelectionsRoute.name]: configGetAgentMcpSelectionsRoute,
  [configGetAcpSharedMcpSelectionsRoute.name]: configGetAcpSharedMcpSelectionsRoute,
  [configSetAcpSharedMcpSelectionsRoute.name]: configSetAcpSharedMcpSelectionsRoute,
  [configGetMcpServersRoute.name]: configGetMcpServersRoute,
  [configGetKnowledgeConfigsRoute.name]: configGetKnowledgeConfigsRoute,
  [configSetKnowledgeConfigsRoute.name]: configSetKnowledgeConfigsRoute,
  [configGetAcpRegistryIconMarkupRoute.name]: configGetAcpRegistryIconMarkupRoute,
  [configGetVoiceAiConfigRoute.name]: configGetVoiceAiConfigRoute,
  [configUpdateVoiceAiConfigRoute.name]: configUpdateVoiceAiConfigRoute,
  [configGetGeminiSafetyRoute.name]: configGetGeminiSafetyRoute,
  [configSetGeminiSafetyRoute.name]: configSetGeminiSafetyRoute,
  [configGetAzureApiVersionRoute.name]: configGetAzureApiVersionRoute,
  [configSetAzureApiVersionRoute.name]: configSetAzureApiVersionRoute,
  [configGetAwsBedrockCredentialRoute.name]: configGetAwsBedrockCredentialRoute,
  [configSetAwsBedrockCredentialRoute.name]: configSetAwsBedrockCredentialRoute,
  [settingsGetSnapshotRoute.name]: settingsGetSnapshotRoute,
  [settingsListSystemFontsRoute.name]: settingsListSystemFontsRoute,
  [settingsUpdateRoute.name]: settingsUpdateRoute,
  [settingsActivityListRoute.name]: settingsActivityListRoute,
  [startupGetBootstrapRoute.name]: startupGetBootstrapRoute
} satisfies Record<string, RouteContract>

const DEEPCHAT_ROUTE_CATALOG_PART_4 = {
  [sessionsCreateRoute.name]: sessionsCreateRoute,
  [sessionsRestoreRoute.name]: sessionsRestoreRoute,
  [sessionsListMessagesPageRoute.name]: sessionsListMessagesPageRoute,
  [sessionsListRoute.name]: sessionsListRoute,
  [sessionsListLightweightRoute.name]: sessionsListLightweightRoute,
  [sessionsGetLightweightByIdsRoute.name]: sessionsGetLightweightByIdsRoute,
  [sessionsActivateRoute.name]: sessionsActivateRoute,
  [sessionsDeactivateRoute.name]: sessionsDeactivateRoute,
  [sessionsGetActiveRoute.name]: sessionsGetActiveRoute,
  [sessionsEnsureAcpDraftRoute.name]: sessionsEnsureAcpDraftRoute,
  [sessionsListPendingInputsRoute.name]: sessionsListPendingInputsRoute,
  [sessionsQueuePendingInputRoute.name]: sessionsQueuePendingInputRoute,
  [sessionsUpdateQueuedInputRoute.name]: sessionsUpdateQueuedInputRoute,
  [sessionsMoveQueuedInputRoute.name]: sessionsMoveQueuedInputRoute,
  [sessionsConvertPendingInputToSteerRoute.name]: sessionsConvertPendingInputToSteerRoute,
  [sessionsSteerPendingInputRoute.name]: sessionsSteerPendingInputRoute,
  [sessionsDeletePendingInputRoute.name]: sessionsDeletePendingInputRoute,
  [sessionsRetryMessageRoute.name]: sessionsRetryMessageRoute,
  [sessionsDeleteMessageRoute.name]: sessionsDeleteMessageRoute,
  [sessionsEditUserMessageRoute.name]: sessionsEditUserMessageRoute,
  [sessionsForkRoute.name]: sessionsForkRoute,
  [sessionsSearchHistoryRoute.name]: sessionsSearchHistoryRoute,
  [sessionsGetSearchResultsRoute.name]: sessionsGetSearchResultsRoute,
  [sessionsGetTapeContextRoute.name]: sessionsGetTapeContextRoute,
  [sessionsListMessageTracesRoute.name]: sessionsListMessageTracesRoute,
  [sessionsExportMessageTapeReplaySliceRoute.name]: sessionsExportMessageTapeReplaySliceRoute,
  [sessionsTranslateTextRoute.name]: sessionsTranslateTextRoute,
  [sessionsGetAgentsRoute.name]: sessionsGetAgentsRoute,
  [sessionsGetUsageDashboardRoute.name]: sessionsGetUsageDashboardRoute,
  [sessionsRetryRtkHealthCheckRoute.name]: sessionsRetryRtkHealthCheckRoute,
  [sessionsRenameRoute.name]: sessionsRenameRoute,
  [sessionsTogglePinnedRoute.name]: sessionsTogglePinnedRoute,
  [sessionsClearMessagesRoute.name]: sessionsClearMessagesRoute,
  [sessionsCompactRoute.name]: sessionsCompactRoute,
  [sessionsExportRoute.name]: sessionsExportRoute,
  [sessionsDeleteRoute.name]: sessionsDeleteRoute,
  [sessionsGetAgentTransferImpactRoute.name]: sessionsGetAgentTransferImpactRoute,
  [sessionsMoveAgentSessionsRoute.name]: sessionsMoveAgentSessionsRoute,
  [sessionsDeleteAgentSessionsRoute.name]: sessionsDeleteAgentSessionsRoute,
  [sessionsMoveToAgentRoute.name]: sessionsMoveToAgentRoute,
  [sessionsGetAcpSessionCommandsRoute.name]: sessionsGetAcpSessionCommandsRoute,
  [sessionsGetAcpSessionConfigOptionsRoute.name]: sessionsGetAcpSessionConfigOptionsRoute,
  [sessionsSetAcpSessionConfigOptionRoute.name]: sessionsSetAcpSessionConfigOptionRoute,
  [sessionsGetPermissionModeRoute.name]: sessionsGetPermissionModeRoute,
  [sessionsSetPermissionModeRoute.name]: sessionsSetPermissionModeRoute,
  [sessionsSetSubagentEnabledRoute.name]: sessionsSetSubagentEnabledRoute,
  [sessionsSetModelRoute.name]: sessionsSetModelRoute,
  [sessionsSetProjectDirRoute.name]: sessionsSetProjectDirRoute,
  [sessionsGetGenerationSettingsRoute.name]: sessionsGetGenerationSettingsRoute,
  [sessionsGetDisabledAgentToolsRoute.name]: sessionsGetDisabledAgentToolsRoute,
  [sessionsUpdateDisabledAgentToolsRoute.name]: sessionsUpdateDisabledAgentToolsRoute,
  [sessionsUpdateGenerationSettingsRoute.name]: sessionsUpdateGenerationSettingsRoute,
  [providersListRoute.name]: providersListRoute,
  [providersListSummariesRoute.name]: providersListSummariesRoute,
  [providersListDefaultsRoute.name]: providersListDefaultsRoute,
  [providersSetByIdRoute.name]: providersSetByIdRoute,
  [providersUpdateRoute.name]: providersUpdateRoute,
  [providersAddRoute.name]: providersAddRoute,
  [providersRemoveRoute.name]: providersRemoveRoute,
  [providersReorderRoute.name]: providersReorderRoute,
  [providersListModelsRoute.name]: providersListModelsRoute,
  [providersTestConnectionRoute.name]: providersTestConnectionRoute,
  [providersGetRateLimitStatusRoute.name]: providersGetRateLimitStatusRoute,
  [providersGetKeyStatusRoute.name]: providersGetKeyStatusRoute,
  [providersUpdateRateLimitRoute.name]: providersUpdateRateLimitRoute,
  [providersGetEmbeddingDimensionsRoute.name]: providersGetEmbeddingDimensionsRoute,
  [providersSyncModelScopeMcpServersRoute.name]: providersSyncModelScopeMcpServersRoute,
  [providersRunAcpDebugActionRoute.name]: providersRunAcpDebugActionRoute,
  [providersRefreshModelsRoute.name]: providersRefreshModelsRoute,
  [providersListOllamaModelsRoute.name]: providersListOllamaModelsRoute,
  [providersListOllamaRunningModelsRoute.name]: providersListOllamaRunningModelsRoute,
  [providersPullOllamaModelRoute.name]: providersPullOllamaModelRoute,
  [providersWarmupAcpProcessRoute.name]: providersWarmupAcpProcessRoute,
  [providersGetAcpProcessConfigOptionsRoute.name]: providersGetAcpProcessConfigOptionsRoute,
  [providersImportScanRoute.name]: providersImportScanRoute,
  [providersImportApplyRoute.name]: providersImportApplyRoute,
  [modelsGetProviderCatalogRoute.name]: modelsGetProviderCatalogRoute,
  [modelsListRuntimeRoute.name]: modelsListRuntimeRoute,
  [modelsSetBatchStatusRoute.name]: modelsSetBatchStatusRoute,
  [modelsSetStatusRoute.name]: modelsSetStatusRoute,
  [modelsAddCustomRoute.name]: modelsAddCustomRoute,
  [modelsRemoveCustomRoute.name]: modelsRemoveCustomRoute,
  [modelsUpdateCustomRoute.name]: modelsUpdateCustomRoute,
  [modelsGetConfigRoute.name]: modelsGetConfigRoute,
  [modelsSetConfigRoute.name]: modelsSetConfigRoute,
  [modelsResetConfigRoute.name]: modelsResetConfigRoute,
  [modelsGetProviderConfigsRoute.name]: modelsGetProviderConfigsRoute,
  [modelsHasUserConfigRoute.name]: modelsHasUserConfigRoute,
  [modelsExportConfigsRoute.name]: modelsExportConfigsRoute,
  [modelsImportConfigsRoute.name]: modelsImportConfigsRoute,
  [modelsGetCapabilitiesRoute.name]: modelsGetCapabilitiesRoute,
  [modelsTranscribeAudioRoute.name]: modelsTranscribeAudioRoute
} satisfies Record<string, RouteContract>

const DEEPCHAT_ROUTE_CATALOG_PART_5 = {
  [chatSendMessageRoute.name]: chatSendMessageRoute,
  [chatSteerActiveTurnRoute.name]: chatSteerActiveTurnRoute,
  [chatStopStreamRoute.name]: chatStopStreamRoute,
  [chatRespondToolInteractionRoute.name]: chatRespondToolInteractionRoute,
  [databaseSecurityGetStatusRoute.name]: databaseSecurityGetStatusRoute,
  [databaseSecurityEnableRoute.name]: databaseSecurityEnableRoute,
  [databaseSecurityChangePasswordRoute.name]: databaseSecurityChangePasswordRoute,
  [databaseSecurityDisableRoute.name]: databaseSecurityDisableRoute,
  [databaseSecurityRepairSchemaRoute.name]: databaseSecurityRepairSchemaRoute,
  [memoryListRoute.name]: memoryListRoute,
  [memorySearchRoute.name]: memorySearchRoute,
  [memoryAddRoute.name]: memoryAddRoute,
  [memoryUpdateRoute.name]: memoryUpdateRoute,
  [memoryGetByIdsRoute.name]: memoryGetByIdsRoute,
  [memoryGetStatusRoute.name]: memoryGetStatusRoute,
  [memoryGetHealthRoute.name]: memoryGetHealthRoute,
  [memoryReindexRoute.name]: memoryReindexRoute,
  [memoryGetLifecycleRoute.name]: memoryGetLifecycleRoute,
  [memoryGetArchiveCandidateLifecyclePreviewRoute.name]:
    memoryGetArchiveCandidateLifecyclePreviewRoute,
  [memoryListAuditEventsRoute.name]: memoryListAuditEventsRoute,
  [memoryListViewManifestsRoute.name]: memoryListViewManifestsRoute,
  [memoryDeleteRoute.name]: memoryDeleteRoute,
  [memoryArchiveRoute.name]: memoryArchiveRoute,
  [memoryClearRoute.name]: memoryClearRoute,
  [memoryRestoreRoute.name]: memoryRestoreRoute,
  [memoryGetSourceSpanRoute.name]: memoryGetSourceSpanRoute,
  [memoryListConflictsRoute.name]: memoryListConflictsRoute,
  [memoryResolveConflictRoute.name]: memoryResolveConflictRoute,
  [memoryListPersonaVersionsRoute.name]: memoryListPersonaVersionsRoute,
  [memoryRollbackPersonaRoute.name]: memoryRollbackPersonaRoute,
  [memoryListPersonaDraftsRoute.name]: memoryListPersonaDraftsRoute,
  [memoryApprovePersonaDraftRoute.name]: memoryApprovePersonaDraftRoute,
  [memoryRejectPersonaDraftRoute.name]: memoryRejectPersonaDraftRoute,
  [memorySetPersonaAnchorRoute.name]: memorySetPersonaAnchorRoute,
  [skillsListMetadataRoute.name]: skillsListMetadataRoute,
  [skillsListCatalogRoute.name]: skillsListCatalogRoute,
  [skillsGetDirectoryRoute.name]: skillsGetDirectoryRoute,
  [skillsInstallFromFolderRoute.name]: skillsInstallFromFolderRoute,
  [skillsInstallFromZipRoute.name]: skillsInstallFromZipRoute,
  [skillsInstallFromUrlRoute.name]: skillsInstallFromUrlRoute,
  [skillsScanGitRepoRoute.name]: skillsScanGitRepoRoute,
  [skillsInstallFromGitRoute.name]: skillsInstallFromGitRoute,
  [skillsGetSyncConfigRoute.name]: skillsGetSyncConfigRoute,
  [skillsSetSyncDirectoryRoute.name]: skillsSetSyncDirectoryRoute,
  [skillsPreviewSyncDirectoryExportRoute.name]: skillsPreviewSyncDirectoryExportRoute,
  [skillsExecuteSyncDirectoryExportRoute.name]: skillsExecuteSyncDirectoryExportRoute,
  [skillsPreviewSyncDirectoryImportRoute.name]: skillsPreviewSyncDirectoryImportRoute,
  [skillsExecuteSyncDirectoryImportRoute.name]: skillsExecuteSyncDirectoryImportRoute,
  [skillsUninstallRoute.name]: skillsUninstallRoute,
  [skillsReadFileRoute.name]: skillsReadFileRoute,
  [skillsUpdateFileRoute.name]: skillsUpdateFileRoute,
  [skillsSaveWithExtensionRoute.name]: skillsSaveWithExtensionRoute,
  [skillsGetFolderTreeRoute.name]: skillsGetFolderTreeRoute,
  [skillsOpenFolderRoute.name]: skillsOpenFolderRoute,
  [skillsGetExtensionRoute.name]: skillsGetExtensionRoute,
  [skillsSaveExtensionRoute.name]: skillsSaveExtensionRoute,
  [skillsListScriptsRoute.name]: skillsListScriptsRoute,
  [skillsGetActiveRoute.name]: skillsGetActiveRoute,
  [skillsSetActiveRoute.name]: skillsSetActiveRoute,
  [skillsSetDisabledRoute.name]: skillsSetDisabledRoute,
  [skillSyncScanExternalToolsRoute.name]: skillSyncScanExternalToolsRoute,
  [skillSyncGetNewDiscoveriesRoute.name]: skillSyncGetNewDiscoveriesRoute,
  [skillSyncAcknowledgeDiscoveriesRoute.name]: skillSyncAcknowledgeDiscoveriesRoute,
  [skillSyncGetRegisteredToolsRoute.name]: skillSyncGetRegisteredToolsRoute,
  [skillSyncScanAgentsRoute.name]: skillSyncScanAgentsRoute,
  [skillSyncGetAgentDetailRoute.name]: skillSyncGetAgentDetailRoute,
  [skillSyncGetAgentSkillDetailRoute.name]: skillSyncGetAgentSkillDetailRoute,
  [skillSyncPreviewAdoptAgentSkillRoute.name]: skillSyncPreviewAdoptAgentSkillRoute,
  [skillSyncExecuteAdoptAgentSkillRoute.name]: skillSyncExecuteAdoptAgentSkillRoute,
  [skillSyncPreviewLinkDeepChatSkillsRoute.name]: skillSyncPreviewLinkDeepChatSkillsRoute,
  [skillSyncExecuteLinkDeepChatSkillsRoute.name]: skillSyncExecuteLinkDeepChatSkillsRoute,
  [skillSyncRepairAgentSkillLinkRoute.name]: skillSyncRepairAgentSkillLinkRoute,
  [skillSyncRemoveAgentSkillLinkRoute.name]: skillSyncRemoveAgentSkillLinkRoute,
  [skillSyncPreviewImportRoute.name]: skillSyncPreviewImportRoute,
  [skillSyncExecuteImportRoute.name]: skillSyncExecuteImportRoute,
  [skillSyncPreviewExportRoute.name]: skillSyncPreviewExportRoute,
  [skillSyncExecuteExportRoute.name]: skillSyncExecuteExportRoute,
  [mcpGetServersRoute.name]: mcpGetServersRoute,
  [mcpGetEnabledRoute.name]: mcpGetEnabledRoute,
  [mcpGetClientsRoute.name]: mcpGetClientsRoute,
  [mcpListToolDefinitionsRoute.name]: mcpListToolDefinitionsRoute,
  [mcpListPromptsRoute.name]: mcpListPromptsRoute,
  [mcpListResourcesRoute.name]: mcpListResourcesRoute,
  [mcpCallToolRoute.name]: mcpCallToolRoute,
  [mcpAddServerRoute.name]: mcpAddServerRoute,
  [mcpUpdateServerRoute.name]: mcpUpdateServerRoute,
  [mcpRemoveServerRoute.name]: mcpRemoveServerRoute,
  [mcpSetServerEnabledRoute.name]: mcpSetServerEnabledRoute,
  [mcpSetEnabledRoute.name]: mcpSetEnabledRoute,
  [mcpIsServerRunningRoute.name]: mcpIsServerRunningRoute,
  [mcpStartServerRoute.name]: mcpStartServerRoute,
  [mcpStopServerRoute.name]: mcpStopServerRoute,
  [mcpGetServerAuthStatusRoute.name]: mcpGetServerAuthStatusRoute,
  [mcpStartServerAuthRoute.name]: mcpStartServerAuthRoute,
  [mcpCompleteServerAuthFromCallbackUrlRoute.name]: mcpCompleteServerAuthFromCallbackUrlRoute,
  [mcpLogoutServerAuthRoute.name]: mcpLogoutServerAuthRoute,
  [mcpGetPromptRoute.name]: mcpGetPromptRoute,
  [mcpReadResourceRoute.name]: mcpReadResourceRoute,
  [mcpSubmitSamplingDecisionRoute.name]: mcpSubmitSamplingDecisionRoute,
  [mcpCancelSamplingRequestRoute.name]: mcpCancelSamplingRequestRoute,
  [mcpGetNpmRegistryStatusRoute.name]: mcpGetNpmRegistryStatusRoute,
  [mcpRefreshNpmRegistryRoute.name]: mcpRefreshNpmRegistryRoute,
  [mcpSetCustomNpmRegistryRoute.name]: mcpSetCustomNpmRegistryRoute,
  [mcpSetAutoDetectNpmRegistryRoute.name]: mcpSetAutoDetectNpmRegistryRoute,
  [mcpClearNpmRegistryCacheRoute.name]: mcpClearNpmRegistryCacheRoute,
  [mcpRouterListServersRoute.name]: mcpRouterListServersRoute,
  [mcpRouterInstallServerRoute.name]: mcpRouterInstallServerRoute,
  [mcpRouterGetApiKeyRoute.name]: mcpRouterGetApiKeyRoute,
  [mcpRouterSetApiKeyRoute.name]: mcpRouterSetApiKeyRoute,
  [mcpRouterIsServerInstalledRoute.name]: mcpRouterIsServerInstalledRoute,
  [mcpRouterUpdateServersAuthRoute.name]: mcpRouterUpdateServersAuthRoute,
  [syncGetBackupStatusRoute.name]: syncGetBackupStatusRoute,
  [syncListBackupsRoute.name]: syncListBackupsRoute,
  [syncStartBackupRoute.name]: syncStartBackupRoute,
  [syncImportRoute.name]: syncImportRoute,
  [syncOpenFolderRoute.name]: syncOpenFolderRoute,
  [syncGetCloudConfigRoute.name]: syncGetCloudConfigRoute,
  [syncSetCloudConfigRoute.name]: syncSetCloudConfigRoute,
  [syncTestCloudRoute.name]: syncTestCloudRoute,
  [syncUploadToCloudRoute.name]: syncUploadToCloudRoute,
  [syncPullFromCloudRoute.name]: syncPullFromCloudRoute,
  [upgradeGetStatusRoute.name]: upgradeGetStatusRoute,
  [upgradeCheckRoute.name]: upgradeCheckRoute,
  [upgradeOpenDownloadRoute.name]: upgradeOpenDownloadRoute,
  [upgradeStartDownloadRoute.name]: upgradeStartDownloadRoute,
  [upgradeMockDownloadedRoute.name]: upgradeMockDownloadedRoute,
  [upgradeClearMockRoute.name]: upgradeClearMockRoute,
  [upgradeRestartToUpdateRoute.name]: upgradeRestartToUpdateRoute,
  [debugCreateMockChatSessionRoute.name]: debugCreateMockChatSessionRoute,
  [dialogRespondRoute.name]: dialogRespondRoute,
  [dialogErrorRoute.name]: dialogErrorRoute,
  [toolsListDefinitionsRoute.name]: toolsListDefinitionsRoute,
  [systemOpenSettingsRoute.name]: systemOpenSettingsRoute
} satisfies Record<string, RouteContract>

export type DeepchatRouteCatalog = typeof DEEPCHAT_ROUTE_CATALOG_PART_1 &
  typeof DEEPCHAT_ROUTE_CATALOG_PART_2 &
  typeof DEEPCHAT_ROUTE_CATALOG_PART_3 &
  typeof DEEPCHAT_ROUTE_CATALOG_PART_4 &
  typeof DEEPCHAT_ROUTE_CATALOG_PART_5

// 显式注解避免再次内联巨型推断类型；值由各块合并而成（路由名互不重叠）。
export const DEEPCHAT_ROUTE_CATALOG: DeepchatRouteCatalog = {
  ...DEEPCHAT_ROUTE_CATALOG_PART_1,
  ...DEEPCHAT_ROUTE_CATALOG_PART_2,
  ...DEEPCHAT_ROUTE_CATALOG_PART_3,
  ...DEEPCHAT_ROUTE_CATALOG_PART_4,
  ...DEEPCHAT_ROUTE_CATALOG_PART_5
}

export type DeepchatRouteName = keyof DeepchatRouteCatalog
export type DeepchatRouteContract<T extends DeepchatRouteName> = DeepchatRouteCatalog[T]
export type DeepchatRouteInput<T extends DeepchatRouteName> = z.input<
  DeepchatRouteContract<T>['input']
>
export type DeepchatRouteOutput<T extends DeepchatRouteName> = z.output<
  DeepchatRouteContract<T>['output']
>

export function hasDeepchatRouteContract(name: string): name is DeepchatRouteName {
  return Object.prototype.hasOwnProperty.call(DEEPCHAT_ROUTE_CATALOG, name)
}

export function getDeepchatRouteContract<T extends DeepchatRouteName>(
  name: T
): DeepchatRouteContract<T> {
  return DEEPCHAT_ROUTE_CATALOG[name]
}
